package com.demo.SensorDataInterpreter.util;

import com.demo.SensorDataInterpreter.dto.SensorDataDTO;
import com.demo.SensorDataInterpreter.entity.SensorStatisticalEntity;
import com.demo.SensorDataInterpreter.entity.SensorOperationalEntity;
import com.demo.SensorDataInterpreter.entity.SensorOperationalEntity.StatusChange;
import com.demo.SensorDataInterpreter.entity.SensorOperationalEntity.EventLocation;
import com.demo.SensorDataInterpreter.entity.SensorOperationalEntity.Geometry;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Utility class for mapping SensorDataDTO to SensorStatisticalEntity and SensorOperationalEntity.
 */
public class SensorDataMapper {

    /**
     * Converts a SensorDataDTO to a SensorStatisticalEntity.
     *
     * @param dto the SensorDataDTO to convert
     * @return the converted SensorStatisticalEntity
     */
    public static SensorStatisticalEntity toStatisticsEntity(SensorDataDTO dto) {
        SensorStatisticalEntity entity = new SensorStatisticalEntity();
        entity.setType(dto.getType());
        entity.setTemperature(dto.getTemperature());
        entity.setAirPressure(dto.getAirPressure());
        entity.setHumidity(dto.getHumidity());
        entity.setLightLevel(dto.getLightLevel());
        entity.setBatteryCharge(dto.getBatteryCharge());
        entity.setBatteryVoltage(dto.getBatteryVoltage());
        entity.setTimestamp(LocalDateTime.now());
        return entity;
    }

    /**
     * Converts SensorDataDTO to SensorOperationalEntity.
     *
     * @param dto the SensorDataDTO to convert
     * @return the converted SensorOperationalEntity
     */
    public static SensorOperationalEntity toOperationalEntity(SensorDataDTO dto) {
        SensorOperationalEntity doc = new SensorOperationalEntity();
        // document id is auto-generated by MongoDB
        // doc.setId(dto.getId()); // Uncomment if you want to set a specific ID
        doc.setType(dto.getType());

        // convert status changes to entity
        if (dto.getStatusChanges() != null) {
            List<StatusChange> changes = dto.getStatusChanges().stream().map(statusDto -> {
                StatusChange statusEntity = new StatusChange();
                statusEntity.setDeviceId(statusDto.getDeviceId());
                statusEntity.setVehicleId(statusDto.getVehicleId());
                statusEntity.setVehicleType(statusDto.getVehicleType());
                statusEntity.setPropulsionType(statusDto.getPropulsionType());
                statusEntity.setEventType(statusDto.getEventType());
                statusEntity.setEventTypeReason(statusDto.getEventTypeReason());
                statusEntity.setEventTime(statusDto.getEventTime());

                // event location to entity
                var geoEntity = new Geometry();
                // null check for geometry info
                if (statusDto.getEventLocation() != null
                        && statusDto.getEventLocation().getGeometry() != null) {
                    var geoDto = statusDto.getEventLocation().getGeometry();
                    geoEntity.setType(geoDto.getType());
                    geoEntity.setCoordinates(geoDto.getCoordinates());
                }
                var loc = new EventLocation();
                loc.setGeometry(geoEntity);
                statusEntity.setEventLocation(loc);

                return statusEntity;
            }).collect(Collectors.toList());

            doc.setStatusChanges(changes);
        }

        return doc;
    }
}
